"""
Django settings for vercel_app project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# 28-10-2025 - loading variables for Django Secret Key + MySQL info
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-=cldztbc4jg&xl0!x673!*v2_=p$$eu)=7*f#d0#zs$44xx-h^'
# 28-10-2025 - The above secret key was rotated and no longer valid !
# Getting the secret key from env locally and from enviroment variable in production
SECRET_KEY=os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# With DEBUG=False 404 errors will be directed to a default 404 template
# Not: Django will display a 404.html if you have created one :-)
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', '.vercel.app']
#ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    # For serving static files
    'django.contrib.staticfiles',

    # For saving media files at Cloudinary
    # Must be below the above line: django.contrib.staticfiles when only use cloudinary for media 
    'cloudinary_storage',
    'cloudinary',
    #'example',

    # Wagtail
    'home',

    # 26-10-2025 - Not working
    #'search'
    
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',

    'modelcluster',
    'taggit',
]

MIDDLEWARE = [
    
    # For serving all kind of static files in a correct way use Debug = False
    # This setting is neeeded for serving static files frontend and backend admin
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
     # Wagtail
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'vercel_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         
         # Initially create the dir 'templates' at root level
         # Root level is fine because there is only one Django App in the Project
         # 'DIRS': [],
        'DIRS': [BASE_DIR / 'templates'],
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vercel_app.wsgi.app'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Note: Django modules for using databases are not support in serverless
# environments like Vercel. You can use a database over HTTP, hosted elsewhere.
# For loval developement only
'''DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}'''

# For authentication of the MySQL Database loaded from .env / environment variables at Vercel
DB_NAME=os.getenv('DB_NAME')
DB_USER=os.getenv('DB_USER')
DB_PASSWORD=os.getenv('DB_PASSWORD')
DB_HOST=os.getenv('DB_HOST')

DATABASES = {
    'default': {
        'ENGINE'  : 'django.db.backends.mysql', 
        'NAME'    : DB_NAME,                  
        'USER'    : DB_USER,                    
        'PASSWORD': DB_PASSWORD,             
        'HOST'    : DB_HOST,

        'PORT'    : 3306,
    }
} 

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Settings for serving all kind of static files for Backend Admin and Frontend:
# Debug = False
STATIC_URL = 'static/'

# Where you put your static files ( The dir static needs to match the above static )
STATIC_ROOT = BASE_DIR/'static' 

# Additional directory from which to load static files if wanted
STATICFILES_DIRS = [
   
   # Extra dir put your files 
   BASE_DIR/'assets' 
]

# Wagtail
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR/'media'

# Cloudinary
# For handeling the media files by Django + Wagtail
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Cloudinary
# For handeling the media files by Django + Wagtail
STORAGES = {
    'default': {"BACKEND":'cloudinary_storage.storage.MediaCloudinaryStorage' },
     "staticfiles": { "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage", }, 
     }

# Wagtail
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000

# Wagtail
WAGTAIL_SITE_NAME = 'My Wagtail Site'

# Wagtail - Prod
WAGTAILADMIN_BASE_URL = 'https://wagtail-demo.vercel.app'

# Cloudinary
# Authentication for cloudinary loaded from .env / environment variables at Vercel
CLOUD_NAME=os.getenv('CLOUD_NAME')
API_KEY=os.getenv('API_KEY')
API_SECRET=os.getenv('API_SECRET')

CLOUDINARY_STORAGE = {

    'CLOUD_NAME': CLOUD_NAME,
    'API_KEY': API_KEY,
    'API_SECRET': API_SECRET
}

# Search
# Not in use at the moment
# https://docs.wagtail.org/en/stable/topics/search/backends.html
'''WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}'''

# Wagtail
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
