"""
Django settings for vercel_app project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# 05-09-2025 - loading variables for Django Secret Key + MySQL info
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=cldztbc4jg&xl0!x673!*v2_=p$$eu)=7*f#d0#zs$44xx-h^'
# 05-09-2025 - The above secret key was rotated and no longer valid !
# Getting the secret key from env locally and from enviroment variable in production
#SECRET_KEY=os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

# With DEBUG=False 404 errors will be directed to a default 404 template
# Not: Django will display a 404.html if you have created one :-)
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', '.vercel.app']
#ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    # For serving static files
    'django.contrib.staticfiles',
    #'example',

    # Wagtail

    'home',

    # 26-10-2025 - Not working
    #'search'
    
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',

    'modelcluster',
    'taggit',
]

MIDDLEWARE = [
    
     # For serving all kind of static files in a correct way use Debug = False
     # This setting is neeeded for serving static files frontend and backend admin
     "whitenoise.middleware.WhiteNoiseMiddleware",

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
     # Wagtail
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'vercel_app.urls'

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         
         # Added the URL for work with templates
         # Initially create the dir 'templates' at root level
         # Root level is fine because there is only one Django App in the Project
        # 'DIRS': [],
       # "DIRS": [
       #     os.path.join(PROJECT_DIR, "templates"),
       # ],
        'DIRS': [BASE_DIR / 'templates'],
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vercel_app.wsgi.app'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Note: Django modules for using databases are not support in serverless
# environments like Vercel. You can use a database over HTTP, hosted elsewhere.

'''DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}'''

'''
import os

from dotenv import load_dotenv

load_dotenv()'''

DB_NAME=os.getenv('DB_NAME')
DB_USER=os.getenv('DB_USER')
DB_PASSWORD=os.getenv('DB_PASSWORD')
DB_HOST=os.getenv('DB_HOST')

DATABASES = {
    'default': {
        'ENGINE'  : 'django.db.backends.mysql', 
        'NAME'    : DB_NAME,                  
        'USER'    : DB_USER,                    
        'PASSWORD': DB_PASSWORD,             
        'HOST'    : DB_HOST,

        'PORT'    : 3306,
    }
} 

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Settings for serving all kind of static files for Backend Admin and Frontend:
# Debug = False
# There are only one Django App in the Project and the dir 'static' and 'assets' are at root level
# Note: Initially create the dir 'static' with your static files a run the command:
# "python manage.py collectstatic" and make a commit to GitHub for be ready for Dev + Prod
# Where Django looks for static files
STATIC_URL = 'static/'

# Where you put your static files ( The dir static needs to match the above static )
STATIC_ROOT = BASE_DIR/'static' 

# Additional directory from which to load static files if wanted
# Note: Create a root level dir 'assets' locally with your additional static files and run: 
# "python manage.py collectstatic"
# Now the static files in the 'assets' dir are copied to the 'static' directory  
# Commit to GitHub for this to work in production ( At Vercel )
STATICFILES_DIRS = [
   
   # Extra dir put your files 
   BASE_DIR/'assets' 
]

# Wagtail
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Wagtail
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000

# Wagtail - Test
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Wagtail
WAGTAIL_SITE_NAME = 'My Wagtail Site'

# Wagtail - Prod
WAGTAILADMIN_BASE_URL = 'http://example.com'


# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
'''WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}'''

# Wagtail
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
